import {
  Browser,
  Browsers,
  GlobeSimple,
  Gear,
  FlagBanner,
  FolderSimpleLock,
  Tag,
  Briefcase,
  ListBullets,
  Folder,
  Question,
  MapPin,
  Pencil,
  Fingerprint,
  House,
} from 'phosphor-react'

export default (S) =>
  S.list()
    .title('Content')
    .items([
      S.listItem()
        .title('Content')
        .icon(Browser)
        .child(
          S.list()
            .title('Content')
            .items([
              S.listItem()
                .title('Home')
                .icon(House)
                .child(
                  S.editor()
                    .title('Home')
                    .schemaType('home')
                    .documentId('home'),
                ),
              S.divider(),
              S.listItem()
                .title('Work')
                .icon(Browser)
                .child(
                  S.list()
                    .title('Work')
                    .items([
                      S.listItem()
                        .title('Selected Work')
                        .icon(Briefcase)
                        .child(
                          S.editor()
                            .title('Selected Work')
                            .schemaType('work')
                            .documentId('work'),
                        ),
                      S.divider(),
                      S.listItem()
                        .title('Projects')
                        .icon(Browsers)
                        .child(S.documentTypeList('project').title('Projects')),

                      S.divider(),
                      S.listItem()
                        .title('Categories')
                        .icon(Tag)
                        .child(
                          S.documentTypeList('category').title('Categories'),
                        ),
                      S.divider(),
                      S.listItem()
                        .title('Locations')
                        .icon(MapPin)
                        .child(
                          S.documentTypeList('location').title('Locations'),
                        ),
                    ]),
                ),
              S.divider(),
              S.listItem()
                .title('Info')
                .icon(Fingerprint)
                .child(
                  S.editor()
                    .title('Info')
                    .schemaType('info')
                    .documentId('info'),
                ),
              S.divider(),
              S.listItem()
                .title('Sketches')
                .icon(Pencil)
                .child(
                  S.editor()
                    .title('Sketches')
                    .schemaType('sketches')
                    .documentId('sketches'),
                ),
            ]),
        ),
      S.divider(),
      S.listItem()
        .title('Settings')
        .child(
          S.list()
            .title('Settings')
            .items([
              S.listItem()
                .title('General')
                .child(
                  S.editor()
                    .id('generalSettings')
                    .schemaType('generalSettings')
                    .documentId('generalSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Header')
                .child(
                  S.editor()
                    .id('headerSettings')
                    .schemaType('headerSettings')
                    .documentId('headerSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Footer')
                .child(
                  S.editor()
                    .id('footerSettings')
                    .schemaType('footerSettings')
                    .documentId('footerSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Default SEO / Share')
                .child(
                  S.editor()
                    .id('seoSettings')
                    .schemaType('seoSettings')
                    .documentId('seoSettings'),
                )
                .icon(GlobeSimple),
            ]),
        )
        .icon(Gear),
    ])
