import {
  Browser,
  Browsers,
  GlobeSimple,
  Gear,
  FlagBanner,
  FolderSimpleLock,
  Tag,
  Briefcase,
  ListBullets,
  Folder,
  Question,
} from 'phosphor-react'

export default (S) =>
  S.list()
    .title('Content')
    .items([
      S.listItem()
        .title('Content')
        .icon(Browser)
        .child(
          S.list()
            .title('Content')
            .items([
              S.listItem()
                .title('Home')
                .icon(ListBullets)
                .child(
                  S.editor()
                    .title('Home')
                    .schemaType('home')
                    .documentId('home'),
                ),
              S.listItem()
                .title('Work')
                .icon(Browser)
                .child(
                  S.list()
                    .title('Work')
                    .items([
                      S.listItem()
                        .title('Selected Work')
                        .icon(Briefcase)
                        .child(
                          S.editor()
                            .title('Selected Work')
                            .schemaType('selectedWork')
                            .documentId('selectedWork'),
                        ),
                      S.divider(),
                      S.listItem()
                        .title('Directory')
                        .icon(ListBullets)
                        .child(
                          S.editor()
                            .title('Directory')
                            .schemaType('directory')
                            .documentId('directory'),
                        ),
                      S.divider(),
                      S.listItem()
                        .title('Projects')
                        .icon(Browsers)
                        .child(S.documentTypeList('project').title('Projects')),
                      S.divider(),
                      S.listItem()
                        .title('Capabilities')
                        .icon(FolderSimpleLock)
                        .child(
                          S.list()
                            .title('Capabilities')
                            .items([
                              S.listItem()
                                .title('General Capability')
                                .icon(FlagBanner)
                                .child(
                                  S.editor()
                                    .title('General Capability')
                                    .schemaType('capabilityGeneral')
                                    .documentId('capabilityGeneral'),
                                ),
                              S.divider(),
                              S.listItem()
                                .title('Individual Capabilities')
                                .icon(Folder)
                                .child(
                                  S.documentTypeList('capability').title(
                                    'Individual Capabilities',
                                  ),
                                ),
                              S.divider(),
                              S.listItem()
                                .title('Project Phases')
                                .icon(Tag)
                                .child(
                                  S.documentTypeList('phase').title(
                                    'Project Phase',
                                  ),
                                ),
                            ]),
                        ),
                      S.divider(),
                      S.listItem()
                        .title('Tags')
                        .icon(Tag)
                        .child(S.documentTypeList('tag').title('Tags')),
                    ]),
                ),
              S.divider(),
              S.listItem()
                .title('Info')
                .icon(Question)
                .child(
                  S.editor()
                    .title('Info')
                    .schemaType('info')
                    .documentId('info'),
                ),
            ]),
        ),
      S.divider(),
      S.listItem()
        .title('Settings')
        .child(
          S.list()
            .title('Settings')
            .items([
              S.listItem()
                .title('General')
                .child(
                  S.editor()
                    .id('generalSettings')
                    .schemaType('generalSettings')
                    .documentId('generalSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Header')
                .child(
                  S.editor()
                    .id('headerSettings')
                    .schemaType('headerSettings')
                    .documentId('headerSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Footer')
                .child(
                  S.editor()
                    .id('footerSettings')
                    .schemaType('footerSettings')
                    .documentId('footerSettings'),
                )
                .icon(Gear),
              S.divider(),
              S.listItem()
                .title('Default SEO / Share')
                .child(
                  S.editor()
                    .id('seoSettings')
                    .schemaType('seoSettings')
                    .documentId('seoSettings'),
                )
                .icon(GlobeSimple),
            ]),
        )
        .icon(Gear),
    ])
